// <auto-generated />

namespace UnityFramework.BattleSystem
{
    public static partial class BuffModifierSystem
    {
        static partial void ConfigureSearchAssembly(ref string assemblyName)
        {
            assemblyName = "Assembly-CSharp";
        }
    }
}
