// <auto-generated />

namespace UnitySisters.Model
{
    public partial class @CharacterFSMModel : UnityFramework.FSM.IFSMParameterBinder
    {
        void UnityFramework.FSM.IFSMParameterBinder.SyncFSMParameters(
            UnityFramework.FSM.IStateMachine stateMachine)
        {
            stateMachine.SetFloat(1979653364, this.@moveValue);
            stateMachine.SetBool(-1913644283, this.@isFalling);
        }
    }
}
