using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;

using UnityEditor;
using UnityEditor.Callbacks;

namespace UnityFramework.BattleSystem.Editor
{
    internal static class BuffModifierSystemSettingsGenerator
    {
        private const string GeneratedSettingsPath =
            "Assets/Plugins/Framework/Runtime/BattleSystem/Buff/Static/" +
            "BuffModifierSystemSettings.generated.cs";
        private const string GeneratedLinkDirectory = "Assets/Generated/UnityFramework";
        private const string GeneratedLinkPath =
            GeneratedLinkDirectory + "/BuffModifierSystem.link.xml";

        [DidReloadScripts]
        private static void OnScriptsReloaded()
        {
            Generate();
        }

        internal static void Generate()
        {
            string assemblyName = BuffModifierSystemSettings.instance.SearchAssemblyName;
            IReadOnlyList<Type> containerTypes = GetContainerTypes(assemblyName);

            bool changed = WriteIfChanged(
                GeneratedSettingsPath,
                BuildGeneratedSettingsSource(assemblyName));

            Directory.CreateDirectory(GeneratedLinkDirectory);
            changed |= WriteIfChanged(
                GeneratedLinkPath,
                BuildLinkXml(assemblyName, containerTypes));

            if (changed)
                AssetDatabase.Refresh();
        }

        internal static IReadOnlyList<Type> GetContainerTypes(string assemblyName)
        {
            return TypeCache.GetTypesWithAttribute<BuffModifierContainerTypeAttribute>()
                .Where(type =>
                    type != null &&
                    !type.IsAbstract &&
                    !type.IsGenericTypeDefinition &&
                    typeof(BuffModifierContainer).IsAssignableFrom(type) &&
                    string.Equals(
                        type.Assembly.GetName().Name,
                        assemblyName,
                        StringComparison.Ordinal))
                .OrderBy(type => type.FullName, StringComparer.Ordinal)
                .ToArray();
        }

        private static string BuildGeneratedSettingsSource(string assemblyName)
        {
            string escapedAssemblyName = assemblyName
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");

            StringBuilder builder = new StringBuilder(512);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine();
            builder.AppendLine("namespace UnityFramework.BattleSystem");
            builder.AppendLine("{");
            builder.AppendLine("    public static partial class BuffModifierSystem");
            builder.AppendLine("    {");
            builder.AppendLine(
                "        static partial void ConfigureSearchAssembly(ref string assemblyName)");
            builder.AppendLine("        {");
            builder.Append("            assemblyName = \"")
                .Append(escapedAssemblyName)
                .AppendLine("\";");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildLinkXml(
            string assemblyName,
            IReadOnlyList<Type> containerTypes)
        {
            StringBuilder builder = new StringBuilder(512);
            builder.AppendLine("<linker>");
            if (containerTypes.Count > 0)
            {
                builder.Append("  <assembly fullname=\"")
                    .Append(SecurityElement.Escape(assemblyName))
                    .AppendLine("\">");
                for (int i = 0; i < containerTypes.Count; i++)
                {
                    builder.Append("    <type fullname=\"")
                        .Append(SecurityElement.Escape(containerTypes[i].FullName))
                        .AppendLine("\" preserve=\"all\" />");
                }
                builder.AppendLine("  </assembly>");
            }
            builder.AppendLine("</linker>");
            return builder.ToString();
        }

        private static bool WriteIfChanged(string path, string contents)
        {
            if (File.Exists(path) &&
                string.Equals(File.ReadAllText(path), contents, StringComparison.Ordinal))
            {
                return false;
            }

            string directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);
            File.WriteAllText(path, contents, new UTF8Encoding(false));
            return true;
        }
    }
}
