// <auto-generated />

namespace @UnitySisters.@BattleSystem
{
    public partial class @CharacterBattleAttributeSet : global::UnityFramework.Utility.IDeepCopyGenerated
    {
        object global::UnityFramework.Utility.IDeepCopyGenerated.DeepCopyGenerated(
            global::UnityFramework.Utility.DeepCopyContext context)
        {
            if (context == null)
                throw new global::System.ArgumentNullException(nameof(context));

            if (context.TryGetCopy(this, out object existingCopy))
                return existingCopy;

            @CharacterBattleAttributeSet copy = (@CharacterBattleAttributeSet)MemberwiseClone();
            context.RegisterCopy(this, copy);
            __DeepCopyFieldsTo_UnitySisters_BattleSystem_CharacterBattleAttributeSet(copy, context);
            return copy;
        }

        protected void __DeepCopyFieldsTo_UnitySisters_BattleSystem_CharacterBattleAttributeSet(@CharacterBattleAttributeSet target,
            global::UnityFramework.Utility.DeepCopyContext context)
        {
            if (this.@hp == null)
                target.@hp = null;
            else if (context.TryGetCopy(this.@hp, out object __hpExistingWrapperCopy))
                target.@hp = (global::@UnityFramework.@ReflectionProperty<global::@System.@Int32>)__hpExistingWrapperCopy;
            else
            {
                global::@UnityFramework.@ReflectionProperty<global::@System.@Int32> __hpWrapperCopy = new global::@UnityFramework.@ReflectionProperty<global::@System.@Int32>();
                context.RegisterCopy(this.@hp, __hpWrapperCopy);
                global::@System.@Int32 __hpWrappedValue = (global::@System.@Int32)this.@hp;
                global::@System.@Int32 __hpCopiedValue = global::UnityFramework.Utility.DeepCopyUtility.CopyReference(__hpWrappedValue, context);
                __hpWrapperCopy.@Value = __hpCopiedValue;
                target.@hp = __hpWrapperCopy;
            }
            if (this.@attack == null)
                target.@attack = null;
            else if (context.TryGetCopy(this.@attack, out object __attackExistingWrapperCopy))
                target.@attack = (global::@UnityFramework.@ReflectionProperty<global::@System.@Single>)__attackExistingWrapperCopy;
            else
            {
                global::@UnityFramework.@ReflectionProperty<global::@System.@Single> __attackWrapperCopy = new global::@UnityFramework.@ReflectionProperty<global::@System.@Single>();
                context.RegisterCopy(this.@attack, __attackWrapperCopy);
                global::@System.@Single __attackWrappedValue = (global::@System.@Single)this.@attack;
                global::@System.@Single __attackCopiedValue = global::UnityFramework.Utility.DeepCopyUtility.CopyReference(__attackWrappedValue, context);
                __attackWrapperCopy.@Value = __attackCopiedValue;
                target.@attack = __attackWrapperCopy;
            }
            if (this.@defense == null)
                target.@defense = null;
            else if (context.TryGetCopy(this.@defense, out object __defenseExistingWrapperCopy))
                target.@defense = (global::@UnityFramework.@ReflectionProperty<global::@System.@Single>)__defenseExistingWrapperCopy;
            else
            {
                global::@UnityFramework.@ReflectionProperty<global::@System.@Single> __defenseWrapperCopy = new global::@UnityFramework.@ReflectionProperty<global::@System.@Single>();
                context.RegisterCopy(this.@defense, __defenseWrapperCopy);
                global::@System.@Single __defenseWrappedValue = (global::@System.@Single)this.@defense;
                global::@System.@Single __defenseCopiedValue = global::UnityFramework.Utility.DeepCopyUtility.CopyReference(__defenseWrappedValue, context);
                __defenseWrapperCopy.@Value = __defenseCopiedValue;
                target.@defense = __defenseWrapperCopy;
            }
        }
    }
}
